name : PMD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs: 

  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
  
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'
      - uses: pmd/pmd-github-action@v2
        with:
          rulesets: ’java-basic’
